duillier_admin_homepage:
    path:     /
    defaults: { _controller: DuillierAdminBundle:Default:index }

duillier_admin_nouveauConcours:
    path:     /nouveauConcours
    defaults: { _controller: DuillierAdminBundle:Default:nouveauConcours }

duillier_admin_gestionClub:
    path:     /gestionClub
    defaults: { _controller: DuillierAdminBundle:Default:gestionClub }

duillier_admin_modifierClub:
    path:     /gestionClub/modifier
    defaults: { _controller: DuillierAdminBundle:Default:modifierClub }

duillier_admin_supprimerClub:
    path:     /gestionClub/supprimer
    defaults: { _controller: DuillierAdminBundle:Default:supprimerClub }

duillier_admin_ajouterClub:
    path:     /gestionClub/ajouter
    defaults: { _controller: DuillierAdminBundle:Default:ajouterClub }

duillier_admin_gererRepas:
    path:     /gererRepas
    defaults: { _controller: DuillierAdminBundle:Default:gererRepas }

duillier_admin_gestionAdmin:
    path:     /gestionAdmin
    defaults: { _controller: DuillierAdminBundle:Default:gestionAdmin }

duillier_admin_supprimerAdmin:
    path:     /supprimerAdmin
    defaults: { _controller: DuillierAdminBundle:Default:supprimerAdmin }


duillier_admin_ajouterAdmin:
    path:     /ajouterAdmin
    defaults: { _controller: DuillierAdminBundle:Default:ajouterAdmin }


duillier_admin_ajoutAdmin:
    path:     /ajoutAdmin
    defaults: { _controller: DuillierAdminBundle:Default:ajoutAdmin }


duillier_admin_connexionAdmin:
    path:     /connexionAdmin
    defaults: { _controller: DuillierAdminBundle:Default:connexionAdmin }


duillier_admin_verifConnexionAdmin:
    path:     /verifConnexionAdmin
    defaults: { _controller: DuillierAdminBundle:Default:verifConnexionAdmin }

duillier_admin_refusConnexion:
    path:     /refusConnexion
    defaults: { _controller: DuillierAdminBundle:Default:refusConnexion }

duillier_admin_gestionRangeur:
    path:     /gestionRangeur
    defaults: { _controller: DuillierAdminBundle:Rangeur:gestionRangeur }

duillier_admin_gestionTireur:
    path:     /gestionTireur
    defaults: { _controller: DuillierAdminBundle:Default:gestionTireur }

duillier_admin_modifierRangeur:
    path:     /modifierRangeur/{idPoste}/{date}/{idHoraire}/{numLivret}/{repas}
    defaults: { _controller: DuillierAdminBundle:Rangeur:modifierRangeur }

duillier_admin_desinscrire:
    path:     /desinscrire/{numLivret}
    defaults: { _controller: DuillierAdminBundle:Rangeur:desinscrire }
