duillier_admin_homepage:
    path:     /
    defaults: { _controller: DuillierAdminBundle:Default:index }

duillier_admin_gestionAdmin:
    path:     gestionAdmin
    defaults: { _controller: DuillierAdminBundle:Default:gestionAdmin }

duillier_admin_supprimerAdmin:
    path:     supprimerAdmin
    defaults: { _controller: DuillierAdminBundle:Default:supprimerAdmin }


duillier_admin_ajouterAdmin:
    path:     ajouterAdmin
    defaults: { _controller: DuillierAdminBundle:Default:ajouterAdmin }


duillier_admin_ajoutAdmin:
    path:     ajoutAdmin
    defaults: { _controller: DuillierAdminBundle:Default:ajoutAdmin }
