duillier_admin:
    resource: "@DuillierAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

duillier_planning:
    resource: "@DuillierPlanningBundle/Resources/config/routing.yml"
    prefix:   /

duillier_sign_in:
    resource: "@DuillierSignInBundle/Resources/config/routing.yml"
    prefix:   /signIn
