<?php

namespace Duillier\PlanningBundle\Repository;

/**
 * OccupeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OccupeRepository extends \Doctrine\ORM\EntityRepository
{
}
