<?php

namespace Duillier\PlanningBundle\Repository;

/**
 * SeComposeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeComposeRepository extends \Doctrine\ORM\EntityRepository
{
}
