<?php

namespace Duillier\PlanningBundle\Repository;

/**
 * TireurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TireurRepository extends \Doctrine\ORM\EntityRepository
{
}
