duillier_planning_homepage:
    path:     /planning
    defaults: { _controller: DuillierPlanningBundle:Default:index }
    path:     /Planning/{page}
    defaults:
        _controller: DuillierPlanningBundle:Default:index
        page:        1
    requirements:
        page: d\*
